#!/usr/bin/env python3
"""
ROM Downloader  (v3.1)

A world-class macOS ROM acquisition tool:

  • Browse a local game catalog; filter by platform; search; multi-select.
  • VERIFIED downloads: for platforms with a No-Intro set on the Internet
    Archive, the exact ROM is matched by title and verified by SHA-1 against
    the archive's published hash — no more wrong-file junk.
  • Best-effort fallback (IA title search) for platforms without a clean set,
    clearly marked "unverified".
  • Concurrent download queue with live per-row status and accurate per-file
    progress (no indeterminate bar).
  • Optional system/BIOS fetch and one-click export to an iCloud Delta folder
    (you pick which platforms — keep the sync small).

Sources are cached in src/sources.json (generated by tools/discover_sources.py).
"""

import tkinter as tk
from tkinter import ttk, messagebox
import threading
import queue
import sqlite3
import requests
import os
import json
import hashlib
import time
import re
import difflib

# ── Paths ────────────────────────────────────────────────────────────────────
HOME = os.path.expanduser("~")
APP_DIR = os.path.dirname(os.path.abspath(__file__))
SUPPORT = os.path.join(HOME, "Library/Application Support/ROMDownloader")
os.makedirs(SUPPORT, exist_ok=True)

DELTA_DIR = os.path.join(HOME, "Library/Mobile Documents/com~apple~CloudDocs/Delta")
SETTINGS_FILE = os.path.join(SUPPORT, "settings.json")
INDEX_CACHE = os.path.join(SUPPORT, "ia_index_cache")
os.makedirs(INDEX_CACHE, exist_ok=True)

IA_SEARCH_URL = "https://archive.org/advancedsearch.php"
IA_DOWNLOAD_BASE = "https://archive.org/download"
IA_META_BASE = "https://archive.org/metadata"
HEADERS = {"User-Agent": "ROM-Downloader/3.1 (moral-video-game-library)"}

ROM_EXTS = {'.zip', '.7z', '.nes', '.sfc', '.smc', '.gba', '.gbc', '.gb',
            '.nds', '.n64', '.z64', '.v64', '.rom', '.img', '.iso', '.bin',
            '.cue', '.dsk', '.adf', '.st', '.d64', '.lnx', '.j64', '.int'}

DEFAULT_SETTINGS = {"concurrency": 3, "verify_hashes": True,
                    "download_os": False, "export_after": False,
                    "library_dir": "", "catalog_db": ""}

# ── Catalog / library location ───────────────────────────────────────────────
# Both are user-configurable (banner + Library row in the UI) and persisted in
# settings. Discovery covers fresh installs, a catalog dropped into App
# Support or next to the app, and pre-3.1 installs that kept everything on an
# external drive.
DEFAULT_LIBRARY_DIR = os.path.join(HOME, "ROM Library")
CATALOG_NAMES = ("moral_video_game_library.db", "retro_catalog.db", "catalog.db")
LEGACY_DIRS = ("/Volumes/x10/Video Games/Games & ROMs",)
CATALOG_URL = "https://github.com/danielalanbates/moral-video-game-library"


def find_catalog(settings):
    """Return the first existing catalog DB path, or ''."""
    cands = [settings.get("catalog_db") or ""]
    roots = [SUPPORT, APP_DIR, settings.get("library_dir") or "", *LEGACY_DIRS]
    for root in roots:
        for name in CATALOG_NAMES:
            if root:
                cands.append(os.path.join(root, name))
    for p in cands:
        if p and os.path.exists(p):
            return p
    return ""


def find_library_dir(settings):
    """Folder ROMs are saved into (created on demand at download time)."""
    if settings.get("library_dir"):
        return settings["library_dir"]
    for d in LEGACY_DIRS:            # keep pre-3.1 installs working unchanged
        if os.path.isdir(d):
            return os.path.join(d, "downloads")
    return DEFAULT_LIBRARY_DIR


# ── Settings ─────────────────────────────────────────────────────────────────
def load_settings():
    s = dict(DEFAULT_SETTINGS)
    try:
        with open(SETTINGS_FILE) as f:
            s.update(json.load(f))
    except Exception:
        pass
    return s


def save_settings(s):
    try:
        with open(SETTINGS_FILE, "w") as f:
            json.dump(s, f, indent=2)
    except Exception:
        pass


def load_sources():
    try:
        with open(os.path.join(APP_DIR, "sources.json")) as f:
            return json.load(f)
    except Exception:
        return {}


# ── Catalog ──────────────────────────────────────────────────────────────────
def list_platforms(db_path):
    if not db_path or not os.path.exists(db_path):
        return []
    con = sqlite3.connect(db_path)
    cur = con.cursor()
    cur.execute("""SELECT p.name, COUNT(*) FROM games g
                   JOIN licensing l ON l.game_id=g.id
                   JOIN platforms p ON p.id=g.platform_id
                   WHERE l.download_allowed=1
                   GROUP BY p.name ORDER BY COUNT(*) DESC""")
    rows = cur.fetchall()
    con.close()
    return rows


def query_games(db_path, platform=None, search=None, limit=5000):
    if not db_path or not os.path.exists(db_path):
        return []
    con = sqlite3.connect(db_path)
    cur = con.cursor()
    sql = """SELECT g.id, g.name, p.name, g.crc, g.md5, g.sha1 FROM games g
             JOIN licensing l ON l.game_id=g.id
             JOIN platforms p ON p.id=g.platform_id
             WHERE l.download_allowed=1"""
    args = []
    if platform and platform != "All platforms":
        sql += " AND p.name=?"
        args.append(platform)
    if search:
        sql += " AND g.name LIKE ?"
        args.append(f"%{search}%")
    sql += " ORDER BY p.name, g.name LIMIT ?"
    args.append(limit)
    cur.execute(sql, args)
    rows = cur.fetchall()
    con.close()
    return rows


# ── Title normalisation & matching ───────────────────────────────────────────
_PAREN = re.compile(r"\([^)]*\)|\[[^]]*\]")
_NONWORD = re.compile(r"[^a-z0-9]+")
REGION_PREF = ["world", "usa", "europe", "japan"]


def norm_title(name):
    base = name.split("(")[0].split("[")[0]
    base = base.lower()
    base = _NONWORD.sub(" ", base).strip()
    return base


def region_rank(filename):
    low = filename.lower()
    for i, r in enumerate(REGION_PREF):
        if f"({r}" in low or f", {r}" in low or f" {r})" in low:
            return i
    return len(REGION_PREF)


def best_match(game_name, files):
    """files: list of dicts with 'name'. Return best dict or None."""
    target = norm_title(game_name)
    if not target:
        return None
    # bucket by normalized base title
    scored = []
    for f in files:
        nm = f["name"]
        base = norm_title(nm)
        if not base:
            continue
        ratio = difflib.SequenceMatcher(None, target, base).ratio()
        # strong boost for exact base-title equality
        if base == target:
            ratio += 0.5
        scored.append((ratio, -region_rank(nm), f))
    if not scored:
        return None
    scored.sort(key=lambda x: (x[0], x[1]), reverse=True)
    best_ratio, _, best_file = scored[0]
    return best_file if best_ratio >= 0.6 else None


# ── IA index (per-platform file list with hashes), cached ────────────────────
class IAIndex:
    def __init__(self):
        self._mem = {}
        self._lock = threading.Lock()

    def for_item(self, ia_item):
        with self._lock:
            if ia_item in self._mem:
                return self._mem[ia_item]
        cache = os.path.join(INDEX_CACHE, ia_item + ".json")
        files = None
        if os.path.exists(cache) and time.time() - os.path.getmtime(cache) < 30 * 86400:
            try:
                with open(cache) as f:
                    files = json.load(f)
            except Exception:
                files = None
        if files is None:
            try:
                r = requests.get(f"{IA_META_BASE}/{ia_item}", timeout=40, headers=HEADERS)
                raw = r.json().get("files", [])
                files = [{"name": x["name"], "sha1": x.get("sha1"),
                          "crc32": x.get("crc32"), "size": x.get("size")}
                         for x in raw
                         if x.get("name", "").lower().endswith(('.7z', '.zip')) and x.get("sha1")]
                with open(cache, "w") as f:
                    json.dump(files, f)
            except Exception:
                files = []
        with self._lock:
            self._mem[ia_item] = files
        return files


# ── Resolution: turn a catalog game into a concrete download ─────────────────
def resolve_verified(game_name, ia_item, index):
    files = index.for_item(ia_item)
    if not files:
        return None
    m = best_match(game_name, files)
    if not m:
        return None
    url = f"{IA_DOWNLOAD_BASE}/{ia_item}/{requests.utils.quote(m['name'])}"
    return {"url": url, "fname": m["name"], "sha1": m.get("sha1"),
            "source": f"No-Intro ({ia_item})", "verified": True}


def resolve_fallback(game_name):
    clean = game_name.split("(")[0].strip()
    params = {"q": f'title:"{clean}" AND mediatype:software',
              "fl[]": ["identifier"], "rows": 8, "output": "json"}
    try:
        docs = requests.get(IA_SEARCH_URL, params=params, timeout=15,
                            headers=HEADERS).json()["response"]["docs"]
    except Exception:
        return None
    for d in docs:
        ident = d["identifier"]
        try:
            files = requests.get(f"{IA_META_BASE}/{ident}/files", timeout=15,
                                 headers=HEADERS).json().get("result", [])
        except Exception:
            continue
        roms = [f for f in files
                if os.path.splitext(f.get("name", ""))[1].lower() in ROM_EXTS]
        if roms:
            f0 = roms[0]
            url = f"{IA_DOWNLOAD_BASE}/{ident}/{requests.utils.quote(f0['name'])}"
            return {"url": url, "fname": f0["name"], "sha1": f0.get("sha1"),
                    "source": "IA search", "verified": False}
    return None


# ── Download job ─────────────────────────────────────────────────────────────
class Job:
    __slots__ = ("iid", "gid", "name", "platform", "status", "pct", "detail")

    def __init__(self, iid, gid, name, platform):
        self.iid = iid
        self.gid = gid
        self.name = name
        self.platform = platform
        self.status = "Queued"
        self.pct = 0
        self.detail = ""


# ── Engine ───────────────────────────────────────────────────────────────────
class Engine:
    def __init__(self, app):
        self.app = app
        self.q = queue.Queue()
        self.index = IAIndex()
        self.sources = load_sources()
        self.workers = []
        self.stop_flag = threading.Event()
        self.active = 0
        self._lock = threading.Lock()

    def submit(self, jobs, concurrency):
        self.stop_flag.clear()
        for j in jobs:
            self.q.put(j)
        n = max(1, min(concurrency, 8))
        for _ in range(n):
            t = threading.Thread(target=self._worker, daemon=True)
            t.start()
            self.workers.append(t)

    def stop(self):
        self.stop_flag.set()
        try:
            while True:
                self.q.get_nowait()
                self.q.task_done()
        except queue.Empty:
            pass

    def _worker(self):
        while not self.stop_flag.is_set():
            try:
                job = self.q.get(timeout=0.5)
            except queue.Empty:
                return
            try:
                self._process(job)
            finally:
                self.q.task_done()

    def _process(self, job):
        self._update(job, "Resolving", 0)
        src = None
        ia_item = (self.sources.get(job.platform) or {}).get("ia_item")
        if ia_item:
            src = resolve_verified(job.name, ia_item, self.index)
        if not src:
            # No verified set match — fall back to IA title search (flagged unverified)
            src = resolve_fallback(job.name)
        if not src:
            self._update(job, "Not found", 0)
            self.app.bump("skipped")
            return
        if self.stop_flag.is_set():
            return

        dest_dir = os.path.join(self.app.download_dir, job.platform)
        os.makedirs(dest_dir, exist_ok=True)
        dest = os.path.join(dest_dir, src["fname"])
        if os.path.exists(dest) and os.path.getsize(dest) > 0:
            self._update(job, "Already have", 100, src["source"])
            self.app.bump("completed")
            return

        self._update(job, "Downloading", 0, src["source"])
        ok, sha = self._download(job, src["url"], dest)
        if not ok:
            self.app.bump("failed")
            self._update(job, "Failed", job.pct, src["source"])
            return

        # Verify
        if self.app.settings.get("verify_hashes") and src.get("sha1"):
            if sha == src["sha1"]:
                self._update(job, "✓ Verified", 100, src["source"])
            else:
                try:
                    os.remove(dest)
                except OSError:
                    pass
                self.app.bump("failed")
                self._update(job, "✗ Hash mismatch", 100, src["source"])
                return
        else:
            tag = "Downloaded" if src["verified"] else "Downloaded (unverified)"
            self._update(job, tag, 100, src["source"])
        self.app.bump("completed")

    def _download(self, job, url, dest):
        tmp = dest + ".part"
        h = hashlib.sha1()
        try:
            r = requests.get(url, stream=True, timeout=40, headers=HEADERS)
            r.raise_for_status()
            total = int(r.headers.get("content-length", 0))
            done = 0
            with open(tmp, "wb") as f:
                for chunk in r.iter_content(chunk_size=131072):
                    if self.stop_flag.is_set():
                        f.close()
                        os.path.exists(tmp) and os.remove(tmp)
                        return False, None
                    if chunk:
                        f.write(chunk)
                        h.update(chunk)
                        done += len(chunk)
                        if total:
                            self._update(job, "Downloading", int(done * 100 / total))
            os.replace(tmp, dest)
            return True, h.hexdigest()
        except Exception:
            if os.path.exists(tmp):
                try:
                    os.remove(tmp)
                except OSError:
                    pass
            return False, None

    def _update(self, job, status, pct, detail=None):
        job.status = status
        job.pct = pct
        if detail is not None:
            job.detail = detail
        self.app.ui_job(job)


# ── App ──────────────────────────────────────────────────────────────────────
class App:
    def __init__(self, root):
        self.root = root
        root.title("ROM Downloader")
        root.geometry("900x680")
        root.minsize(820, 600)
        self.settings = load_settings()
        self.sources = load_sources()
        self.db_path = find_catalog(self.settings)
        self.download_dir = find_library_dir(self.settings)
        self.counts = {"completed": 0, "failed": 0, "skipped": 0}
        self.row_meta = {}
        self.engine = Engine(self)
        self._set_app_icon()
        self._style()
        self._build()
        self._refresh_platforms()
        self._reload()

    def _set_app_icon(self):
        """Window + Dock icon at runtime (the process is python, not the bundle)."""
        try:
            png = os.path.join(APP_DIR, "AppIcon.png")
            if os.path.exists(png):
                self.root.iconphoto(True, tk.PhotoImage(file=png))
        except Exception:
            pass
        try:
            from AppKit import NSApplication, NSImage
            icns = os.path.join(APP_DIR, "AppIcon.icns")
            if os.path.exists(icns):
                img = NSImage.alloc().initWithContentsOfFile_(icns)
                if img:
                    NSApplication.sharedApplication().setApplicationIconImage_(img)
        except Exception:
            pass

    def _style(self):
        st = ttk.Style()
        try:
            st.theme_use("clam")
        except tk.TclError:
            pass
        bg, fg, sel = "#1e1e1e", "#e8e8e8", "#0a84ff"
        self.root.configure(bg=bg)
        st.configure(".", background=bg, foreground=fg, fieldbackground="#2a2a2a")
        st.configure("Treeview", background="#252525", fieldbackground="#252525",
                     foreground=fg, rowheight=24, borderwidth=0)
        st.configure("Treeview.Heading", background="#333", foreground=fg)
        st.map("Treeview", background=[("selected", sel)])
        st.configure("TButton", background="#3a3a3a", foreground=fg)
        st.map("TButton", background=[("active", "#4a4a4a")])
        st.configure("Accent.TButton", background=sel, foreground="white")
        st.map("Accent.TButton", background=[("active", "#3094ff")])
        self.C = dict(bg=bg, fg=fg, sel=sel)

    def _build(self):
        bg, fg = self.C["bg"], self.C["fg"]
        top = tk.Frame(self.root, bg=bg)
        top.pack(fill="x", padx=14, pady=(12, 4))
        tk.Label(top, text="ROM Downloader", font=("Helvetica", 18, "bold"),
                 bg=bg, fg=fg).pack(side="left")
        self.cov_var = tk.StringVar(value="")
        tk.Label(top, textvariable=self.cov_var, bg=bg, fg="#7fd17f").pack(side="right")

        # Catalog banner — shown only when no catalog is found anywhere.
        self.banner = tk.Frame(self.root, bg=bg)
        self.banner.pack(fill="x", padx=14)
        tk.Label(self.banner,
                 text="⚠ No game catalog found. Locate your catalog database, "
                      "or get one from the Moral Video Game Library.",
                 bg=bg, fg="#ff6b6b", wraplength=860, justify="left").pack(side="left")
        ttk.Button(self.banner, text="Locate Catalog…",
                   command=self._locate_catalog).pack(side="right", padx=4)
        ttk.Button(self.banner, text="Get Catalog",
                   command=lambda: __import__("webbrowser").open(CATALOG_URL)
                   ).pack(side="right", padx=4)
        if self.db_path:
            self.banner.pack_forget()

        # Library location row — where downloads are stored.
        lib = tk.Frame(self.root, bg=bg)
        lib.pack(fill="x", padx=14, pady=(4, 0))
        tk.Label(lib, text="Library:", bg=bg, fg=fg).pack(side="left")
        self.lib_var = tk.StringVar(value=self.download_dir)
        tk.Label(lib, textvariable=self.lib_var, bg=bg, fg="#9a9a9a").pack(side="left", padx=6)
        ttk.Button(lib, text="Change…", command=self._choose_library).pack(side="left", padx=4)

        filt = tk.Frame(self.root, bg=bg)
        filt.pack(fill="x", padx=14, pady=6)
        tk.Label(filt, text="Platform:", bg=bg, fg=fg).pack(side="left")
        self.platform_var = tk.StringVar(value="All platforms")
        self.platform_menu = ttk.Combobox(filt, textvariable=self.platform_var,
                                           state="readonly", width=40)
        self.platform_menu.pack(side="left", padx=(4, 12))
        self.platform_menu.bind("<<ComboboxSelected>>", lambda e: self._reload())
        tk.Label(filt, text="Search:", bg=bg, fg=fg).pack(side="left")
        self.search_var = tk.StringVar()
        e = tk.Entry(filt, textvariable=self.search_var, width=22,
                     bg="#2a2a2a", fg=fg, insertbackground=fg)
        e.pack(side="left", padx=4)
        e.bind("<Return>", lambda ev: self._reload())
        ttk.Button(filt, text="Filter", command=self._reload).pack(side="left", padx=4)

        # Tree with status column
        tf = tk.Frame(self.root, bg=bg)
        tf.pack(fill="both", expand=True, padx=14)
        cols = ("name", "platform", "status")
        self.tree = ttk.Treeview(tf, columns=cols, show="headings", selectmode="extended")
        self.tree.heading("name", text="Game")
        self.tree.heading("platform", text="Platform")
        self.tree.heading("status", text="Status")
        self.tree.column("name", width=420)
        self.tree.column("platform", width=240)
        self.tree.column("status", width=180)
        self.tree.tag_configure("ok", foreground="#5fd75f")
        self.tree.tag_configure("bad", foreground="#ff6b6b")
        self.tree.tag_configure("work", foreground="#5fafff")
        vsb = ttk.Scrollbar(tf, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=vsb.set)
        self.tree.pack(side="left", fill="both", expand=True)
        vsb.pack(side="right", fill="y")

        sel = tk.Frame(self.root, bg=bg)
        sel.pack(fill="x", padx=14, pady=(6, 0))
        ttk.Button(sel, text="Select All (shown)",
                   command=lambda: self.tree.selection_set(self.tree.get_children())).pack(side="left")
        ttk.Button(sel, text="Clear",
                   command=lambda: self.tree.selection_remove(self.tree.selection())).pack(side="left", padx=6)
        self.count_var = tk.StringVar(value="0 shown")
        tk.Label(sel, textvariable=self.count_var, bg=bg, fg=fg).pack(side="right")

        # Options
        opt = tk.Frame(self.root, bg=bg)
        opt.pack(fill="x", padx=14, pady=6)
        self.verify_var = tk.BooleanVar(value=self.settings.get("verify_hashes", True))
        self.os_var = tk.BooleanVar(value=self.settings.get("download_os", False))
        self.export_var = tk.BooleanVar(value=self.settings.get("export_after", False))
        for txt, var in [("Verify SHA-1 (reject wrong files)", self.verify_var),
                         ("Download OS / system files", self.os_var),
                         ("Export to Delta after", self.export_var)]:
            tk.Checkbutton(opt, text=txt, variable=var, bg=bg, fg=fg, selectcolor="#2a2a2a",
                           activebackground=bg, activeforeground=fg,
                           command=self._persist).pack(side="left", padx=(0, 14))
        tk.Label(opt, text="Parallel:", bg=bg, fg=fg).pack(side="left")
        self.conc_var = tk.IntVar(value=self.settings.get("concurrency", 3))
        tk.Spinbox(opt, from_=1, to=8, width=3, textvariable=self.conc_var,
                   command=self._persist).pack(side="left", padx=4)

        # Progress summary
        self.summary_var = tk.StringVar(value="Idle.")
        tk.Label(self.root, textvariable=self.summary_var, bg=bg, fg=fg,
                 font=("Helvetica", 11)).pack(pady=(2, 0))

        btns = tk.Frame(self.root, bg=bg)
        btns.pack(pady=10)
        self.dl_btn = ttk.Button(btns, text="⬇  Download Selected", style="Accent.TButton",
                                 command=self.start)
        self.dl_btn.pack(side="left", padx=6)
        ttk.Button(btns, text="⏹ Stop", command=self.stop).pack(side="left", padx=6)
        ttk.Button(btns, text="📁 Export to Delta", command=self.export_to_delta).pack(side="left", padx=6)

    # ---- catalog / library pickers ----
    def _locate_catalog(self):
        from tkinter import filedialog
        p = filedialog.askopenfilename(
            title="Locate catalog database",
            filetypes=[("SQLite database", "*.db *.sqlite *.sqlite3"), ("All files", "*")])
        if not p:
            return
        try:
            con = sqlite3.connect(p)
            con.execute("SELECT 1 FROM games LIMIT 1")
            con.execute("SELECT 1 FROM platforms LIMIT 1")
            con.close()
        except Exception:
            messagebox.showerror("ROM Downloader",
                                 "That file isn't a compatible game catalog "
                                 "(needs 'games' and 'platforms' tables).")
            return
        self.settings["catalog_db"] = p
        save_settings(self.settings)
        self.db_path = p
        self.banner.pack_forget()
        self._refresh_platforms()
        self._reload()

    def _choose_library(self):
        from tkinter import filedialog
        d = filedialog.askdirectory(title="Choose where to store your ROM library",
                                    initialdir=self.download_dir
                                    if os.path.isdir(self.download_dir) else HOME)
        if not d:
            return
        self.settings["library_dir"] = d
        save_settings(self.settings)
        self.download_dir = d
        self.lib_var.set(d)

    # ---- data ----
    def _persist(self):
        self.settings.update(verify_hashes=self.verify_var.get(),
                             download_os=self.os_var.get(),
                             export_after=self.export_var.get(),
                             concurrency=self.conc_var.get())
        save_settings(self.settings)

    def _refresh_platforms(self):
        plats = list_platforms(self.db_path)
        verified = sum(1 for n, _ in plats if n in self.sources)
        self.cov_var.set(f"{verified}/{len(plats)} platforms hash-verified")
        self._plat_names = ["All platforms"] + [n for n, _ in plats]
        vals = ["All platforms"]
        for n, c in plats:
            tag = "  ✓" if n in self.sources else ""
            vals.append(f"{n}  ({c}){tag}")
        self.platform_menu["values"] = vals

    def _sel_platform(self):
        i = self.platform_menu.current()
        return self._plat_names[i] if i >= 0 else "All platforms"

    def _reload(self):
        for iid in self.tree.get_children():
            self.tree.delete(iid)
        self.row_meta.clear()
        rows = query_games(self.db_path, self._sel_platform(), self.search_var.get().strip() or None)
        for gid, name, plat, crc, md5, sha1 in rows:
            verified = plat in self.sources
            tag = "ok" if verified else ""
            iid = self.tree.insert("", "end", values=(name, plat, "✓ verified src" if verified else "—"),
                                   tags=(tag,) if tag else ())
            self.row_meta[iid] = (gid, name, plat)
        self.count_var.set(f"{len(rows)} shown")

    # ---- engine callbacks (main thread) ----
    def ui_job(self, job):
        def apply():
            label = job.status
            if job.status == "Downloading":
                label = f"Downloading {job.pct}%"
            tag = ("ok" if job.status.startswith("✓") or "Downloaded" in job.status
                   else "bad" if job.status.startswith("✗") or job.status in ("Failed", "Not found")
                   else "work")
            if self.tree.exists(job.iid):
                vals = self.tree.item(job.iid, "values")
                self.tree.item(job.iid, values=(vals[0], vals[1], label), tags=(tag,))
            self._summary()
        self.root.after(0, apply)

    def bump(self, key):
        self.counts[key] += 1
        self.root.after(0, self._summary)

    def _summary(self):
        c = self.counts
        self.summary_var.set(f"Completed: {c['completed']}   Failed: {c['failed']}   "
                             f"Skipped: {c['skipped']}")

    # ---- controls ----
    def start(self):
        sel = self.tree.selection()
        if not sel:
            messagebox.showinfo("ROM Downloader", "Select one or more games first.")
            return
        self._persist()
        self.counts = {"completed": 0, "failed": 0, "skipped": 0}
        os.makedirs(self.download_dir, exist_ok=True)
        jobs = []
        for iid in sel:
            gid, name, plat = self.row_meta[iid]
            jobs.append(Job(iid, gid, name, plat))
        self.dl_btn.config(state="disabled")
        self.summary_var.set(f"Queued {len(jobs)} downloads…")
        self.engine.submit(jobs, self.conc_var.get())
        threading.Thread(target=self._await_done, args=(len(jobs),), daemon=True).start()

    def _await_done(self, n):
        self.engine.q.join()
        # optional OS/system files for touched platforms
        if self.os_var.get() and not self.engine.stop_flag.is_set():
            self._fetch_system_files()
        self.root.after(0, lambda: self.dl_btn.config(state="normal"))
        self.root.after(0, lambda: self.summary_var.set(
            f"Done.  Completed: {self.counts['completed']}  "
            f"Failed: {self.counts['failed']}  Skipped: {self.counts['skipped']}"))
        if self.export_var.get() and self.counts["completed"]:
            self.root.after(0, self.export_to_delta)

    def _fetch_system_files(self):
        # Best-effort BIOS via IA, per platform downloaded this run
        done_plats = {self.row_meta[i][2] for i in self.tree.selection()}
        for plat in sorted(done_plats):
            short = plat.split(" - ")[-1]
            params = {"q": f'"{short}" AND (title:bios OR title:firmware) AND mediatype:software',
                      "fl[]": ["identifier"], "rows": 4, "output": "json"}
            try:
                docs = requests.get(IA_SEARCH_URL, params=params, timeout=15,
                                    headers=HEADERS).json()["response"]["docs"]
            except Exception:
                continue
            for d in docs:
                ident = d["identifier"]
                try:
                    files = requests.get(f"{IA_META_BASE}/{ident}/files", timeout=15,
                                         headers=HEADERS).json().get("result", [])
                except Exception:
                    continue
                bios = [f for f in files if any(k in f.get("name", "").lower()
                        for k in ("bios", "firmware")) and os.path.splitext(
                        f.get("name", ""))[1].lower() in {'.bin', '.rom', '.zip'}]
                if bios:
                    sysdir = os.path.join(self.download_dir, plat, "_system")
                    os.makedirs(sysdir, exist_ok=True)
                    fn = bios[0]["name"]
                    dest = os.path.join(sysdir, fn)
                    if not os.path.exists(dest):
                        url = f"{IA_DOWNLOAD_BASE}/{ident}/{requests.utils.quote(fn)}"
                        try:
                            r = requests.get(url, timeout=40, headers=HEADERS)
                            with open(dest, "wb") as f:
                                f.write(r.content)
                        except Exception:
                            pass
                    break

    def stop(self):
        self.engine.stop()
        self.summary_var.set("Stopping…")

    # ---- Delta export ----
    def export_to_delta(self):
        if not os.path.isdir(self.download_dir):
            messagebox.showinfo("Export to Delta", "Nothing downloaded yet.")
            return
        plats = []
        for entry in sorted(os.listdir(self.download_dir)):
            pdir = os.path.join(self.download_dir, entry)
            if not os.path.isdir(pdir):
                continue
            files = _iter_roms(pdir)
            if files:
                plats.append((entry, len(files), sum(os.path.getsize(f) for f in files)))
        if not plats:
            messagebox.showinfo("Export to Delta", "No downloaded ROMs to export.")
            return
        ExportDialog(self.root, plats, self._do_export, self.C)

    def _do_export(self, chosen):
        import shutil
        os.makedirs(DELTA_DIR, exist_ok=True)
        copied = 0
        for plat in chosen:
            src = os.path.join(self.download_dir, plat)
            dst = os.path.join(DELTA_DIR, plat)
            os.makedirs(dst, exist_ok=True)
            for f in _iter_roms(src):
                t = os.path.join(dst, os.path.basename(f))
                if not os.path.exists(t):
                    try:
                        shutil.copy2(f, t)
                        copied += 1
                    except Exception:
                        pass
        messagebox.showinfo("Export to Delta",
                            f"Exported {copied} file(s) for {len(chosen)} platform(s) to:\n{DELTA_DIR}")


def _iter_roms(folder):
    out = []
    for r, _d, files in os.walk(folder):
        if os.path.basename(r) == "_system":
            continue
        for f in files:
            if f.endswith(".part"):
                continue
            if os.path.splitext(f)[1].lower() in ROM_EXTS:
                out.append(os.path.join(r, f))
    return out


class ExportDialog(tk.Toplevel):
    def __init__(self, parent, plats, on_confirm, C):
        super().__init__(parent)
        self.title("Export to Delta")
        self.geometry("540x480")
        self.configure(bg=C["bg"])
        self.on_confirm = on_confirm
        tk.Label(self, text="Choose platforms to copy into Delta",
                 font=("Helvetica", 13, "bold"), bg=C["bg"], fg=C["fg"]).pack(pady=8)
        tk.Label(self, text="Pick only a few — keep the iCloud Delta sync small.",
                 bg=C["bg"], fg="#999").pack()
        body = tk.Frame(self, bg=C["bg"])
        body.pack(fill="both", expand=True, padx=16, pady=8)
        self.vars = {}
        for name, n, size in plats:
            v = tk.BooleanVar(value=False)
            self.vars[name] = v
            tk.Checkbutton(body, text=f"{name}   —   {n} file(s), {size/1048576:.1f} MB",
                           variable=v, anchor="w", bg=C["bg"], fg=C["fg"],
                           selectcolor="#2a2a2a", activebackground=C["bg"],
                           activeforeground=C["fg"]).pack(fill="x")
        bf = tk.Frame(self, bg=C["bg"])
        bf.pack(pady=10)
        ttk.Button(bf, text="Export Selected", command=self._confirm).pack(side="left", padx=6)
        ttk.Button(bf, text="Cancel", command=self.destroy).pack(side="left", padx=6)

    def _confirm(self):
        chosen = [n for n, v in self.vars.items() if v.get()]
        if not chosen:
            messagebox.showinfo("Export to Delta", "Pick at least one platform.")
            return
        self.destroy()
        self.on_confirm(chosen)


if __name__ == "__main__":
    root = tk.Tk()
    app = App(root)
    root.mainloop()
